import React, { useState } from 'react';
import { CheckCircle2, AlertTriangle, Hammer, Copy, Check, ShieldCheck, Info } from 'lucide-react';
import type { VerdictResponse } from '../../types/api';
import './VerdictCard.css';

interface VerdictCardProps {
  verdict: VerdictResponse;
  packageName: string;
  system: string;
  userRequirement?: string;
}

export const VerdictCard: React.FC<VerdictCardProps> = ({
  verdict,
  packageName,
  system,
  userRequirement,
}) => {
  const [copied, setCopied] = useState(false);
  const [showFactors, setShowFactors] = useState(false);

  const getVerdictTheme = (decision: string) => {
    switch (decision) {
      case 'BORROW':
        return {
          label: 'BORROW',
          title: 'Safe to Borrow Dependency',
          subtitle: 'The package is mature, active, or stable for your requirement.',
          icon: CheckCircle2,
          className: 'verdict-borrow',
        };
      case 'MIGRATE':
        return {
          label: 'MIGRATE',
          title: 'Migrate to Alternative Dependency',
          subtitle: 'Package exhibits maintenance stagnation, unaddressed bugs, or security risks.',
          icon: AlertTriangle,
          className: 'verdict-migrate',
        };
      case 'BUILD':
        return {
          label: 'BUILD',
          title: 'Build Zero-Dependency Snippet',
          subtitle: 'Your feature requirement is light enough to build directly without third-party bloat.',
          icon: Hammer,
          className: 'verdict-build',
        };
      case 'UNVERIFIED_CANDIDATES':
        return {
          label: 'UNVERIFIED CANDIDATES',
          title: 'Candidate Packages Unverified in Registry',
          subtitle: 'Could not verify candidate packages in registry for this complex task. Evaluate by exact package name.',
          icon: AlertTriangle,
          className: 'verdict-migrate',
        };
      default:
        return {
          label: decision,
          title: 'Evaluation Verdict Reached',
          subtitle: 'Analysis complete.',
          icon: ShieldCheck,
          className: 'verdict-borrow',
        };
    }
  };

  const theme = getVerdictTheme(verdict.decision);
  const IconComponent = theme.icon;

  const handleCopyMarkdown = () => {
    const mdContent = `
# BuildOrBorrow Audit Report: ${packageName} (${system.toUpperCase()})

**Final Decision:** \`${verdict.decision}\`
**Confidence Score:** ${(verdict.confidence_score * 100).toFixed(0)}% (${verdict.confidence_level})
**Requirement:** ${userRequirement || 'General usage'}

## Key Architectural Reasoning:
${verdict.reasoning.map((r) => `- ${r}`).join('\n')}

${
  verdict.decision === 'MIGRATE' && verdict.recommended_alternative
    ? `**Recommended Alternative:** \`${verdict.recommended_alternative}\` (${verdict.recommended_alternative_system || system})`
    : ''
}
${verdict.decision === 'BUILD' && verdict.estimated_build_effort ? `**Estimated Build Effort:** ${verdict.estimated_build_effort}` : ''}

## Confidence Factors:
${verdict.confidence_factors.map((f) => `- ${f}`).join('\n')}

---
*Report generated by BuildOrBorrow AI Decision Engine*
`.trim();

    navigator.clipboard.writeText(mdContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={`ui-card verdict-card ${theme.className}`}>
      {/* Top Banner */}
      <div className="verdict-header">
        <div className="verdict-badge-row">
          <div className="verdict-pill">
            <IconComponent className="verdict-icon" />
            <span className="verdict-label">{theme.label}</span>
          </div>

          <div className="confidence-pill">
            <ShieldCheck className="conf-icon" />
            <span>Confidence: {(verdict.confidence_score * 100).toFixed(0)}% ({verdict.confidence_level})</span>
            <button
              type="button"
              className="info-toggle-btn"
              onClick={() => setShowFactors(!showFactors)}
              title="Toggle Confidence Calculation Breakdown"
            >
              <Info className="info-icon" />
            </button>
          </div>
        </div>

        <button type="button" className="ui-action-btn copy-md-btn" onClick={handleCopyMarkdown}>
          {copied ? (
            <>
              <Check className="copy-icon" />
              <span>Copied Report!</span>
            </>
          ) : (
            <>
              <Copy className="copy-icon" />
              <span>Copy as Markdown</span>
            </>
          )}
        </button>
      </div>

      {/* Main Verdict Content */}
      <div className="verdict-body">
        <h2 className="verdict-title">{theme.title}</h2>
        <p className="verdict-subtitle">{theme.subtitle}</p>

        {/* MIGRATE Recommendation Banner */}
        {verdict.decision === 'MIGRATE' && verdict.recommended_alternative && (
          <div className="migrate-recommendation-box">
            <strong>Recommended Switch:</strong> Migrate from <code>{packageName}</code> to{' '}
            <code className="alt-code">{verdict.recommended_alternative}</code> ({verdict.recommended_alternative_system || system})
          </div>
        )}

        {/* BUILD Effort Banner */}
        {verdict.decision === 'BUILD' && verdict.estimated_build_effort && (
          <div className="build-effort-box">
            <strong>Estimated Implementation Effort:</strong> {verdict.estimated_build_effort}
          </div>
        )}

        {/* Key Reasoning Bullets */}
        <div className="verdict-reasoning">
          <h3>Architectural Reasoning:</h3>
          <ul>
            {verdict.reasoning.map((bullet, idx) => (
              <li key={idx}>
                <span className="bullet-point">•</span>
                <span>{bullet}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Confidence Calculation Breakdown (Collapsible) */}
        {showFactors && (
          <div className="confidence-factors-box">
            <h4>Formulaic Confidence Score Factors:</h4>
            <ul>
              {verdict.confidence_factors.map((factor, idx) => (
                <li key={idx}>{factor}</li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
};
