import os
from typing import Optional
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """
    Centralized Application Settings & Pipeline Limits.
    Loaded from environment variables and/or .env file.
    Follows 12-factor app principles for dev/prod environment portability.
    """
    PROJECT_NAME: str = "BuildOrBorrow API"
    API_V1_STR: str = "/api/v1"
    
    # GCP Configuration
    GCP_PROJECT: Optional[str] = None
    
    # API Keys & Credentials
    GEMINI_API_KEY: Optional[str] = None
    GITHUB_TOKEN: Optional[str] = None
    
    # =========================================================================
    # BIGQUERY BYTE SAFETY CAPS & DEPLOYMENT TOGGLE
    # =========================================================================
    # Master Toggle: Set to True for internal testing to enforce maximum_bytes_billed caps.
    # Set to False for production deployment so BigQuery queries execute without byte limit restrictions.
    ENABLE_BIGQUERY_BYTE_LIMITS: bool = True

    # BigQuery Query Byte Limits (Applied ONLY when ENABLE_BIGQUERY_BYTE_LIMITS is True)
    BQ_DEFAULT_MAX_ALLOWED_MB: float = 500.0        # Default fallback limit for general metadata queries
    BQ_DEPS_DEV_MAX_ALLOWED_MB: float = 2500.0      # Hard cap for deps.dev package resolution, advisories & dependencies queries
    BQ_GH_ARCHIVE_MAX_ALLOWED_MB: float = 9000.0   # Hard cap for multi-week GH Archive activity scans & ARIMA ML forecast (~16 GB)

    # =========================================================================
    # TIME WINDOWS, LOOKBACK & FORECAST HORIZONS
    # =========================================================================
    DEPS_DEV_PARTITION_DAYS: int = 30               # Partition pruning window for deps.dev BigQuery queries (SnapshotAt)
    DEFAULT_LOOKBACK_WEEKS: int = 5                # Default historical lookback period in weeks for GH Archive query
    MAX_LOOKBACK_WEEKS: int = 104                   # Maximum historical lookback period in weeks (2 years / 728 days)
    DEFAULT_FORECAST_WEEKS: int = 13                # Forecast horizon in weeks (~90 days / 13 future weeks)

    # =========================================================================
    # GITHUB API CONFIGURATION & LIMITS
    # =========================================================================
    GITHUB_ISSUES_MAX_COUNT: int = 15               # Maximum recent open GitHub issue titles to fetch for Diagnosis Agent
    GITHUB_ISSUES_REST_PER_PAGE: int = 30           # Number of items requested per page in REST fallback to filter out PRs
    GITHUB_API_TIMEOUT_SECONDS: float = 5.0         # HTTP request timeout in seconds for GitHub API calls

    # =========================================================================
    # GENERATIVE AI (GEMINI) AGENT CONFIGURATION
    # =========================================================================
    GEMINI_MODEL_NAME: str = "gemini-2.5-flash"          # Primary Gemini model used across all AI agents
    FALLBACK_GEMINI_MODEL_NAME: str = "gemini-1.5-flash" # Fallback model if primary experiences 503 capacity spikes
    GEMINI_DEFAULT_TEMPERATURE: float = 0.1             # Low temperature for deterministic output (Candidate, Diagnosis, Verdict)
    GEMINI_BUILDER_TEMPERATURE: float = 0.2             # Slightly higher temperature for creative zero-dep code snippet generation
    CANDIDATE_FINDER_COUNT: int = 3                     # Exact candidate packages count generated by Candidate Finder Agent

    model_config = SettingsConfigDict(
        env_file=("../.env", ".env"),
        env_file_encoding="utf-8",
        extra="ignore"
    )

    def get_gcp_project(self) -> Optional[str]:
        """
        Resolves active GCP Project ID with fallbacks:
        1. Explicit settings.GCP_PROJECT
        2. System env var GOOGLE_CLOUD_PROJECT
        3. System env var GCP_PROJECT
        """
        return (
            self.GCP_PROJECT
            or os.getenv("GCP_PROJECT")
            or os.getenv("GOOGLE_CLOUD_PROJECT")
        )


settings = Settings()
